# gh-pages required settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


# Site settings
sass:
  sass_dir:         _sass
  style:            :compressed

markdown:           kramdown
permalink:          pretty

title: sirM1sterTV
email: thesir@sirm1ster.tv
description: >- # this means to ignore newlines until "baseurl:"
  A Dutch Twitch Affiliate part-time streamer who's main concern is to play games in style and creating a warm and welcoming, inclusive community
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sirm1ster.github.io/sirm1ster.tv" # the base hostname & protocol for your site, e.g. http://example.com

author: sirM1ster
twitch_username: sirm1stertv
twitter_username: sirm1stertv
github_username:  mistermark
youtube_id: UCX2ZZR8I9g5ziJf5W_DOROA

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_tagmanager: GTM-WGZD9XV
google_tgm_trackingParam: tgm_sirm1s
